CREATE TABLE wa_user (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    worldanvil_id TEXT NOT NULL,
    name TEXT NOT NULL,
    avatar_url TEXT,
    last_seen TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE world (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT REFERENCES wa_user(id) ON DELETE CASCADE,
    worldanvil_id TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE article (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT REFERENCES wa_user(id) ON DELETE CASCADE,
    world_id BIGINT REFERENCES world(id) ON DELETE CASCADE,
    worldanvil_id TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    last_checked TIMESTAMP WITH TIME ZONE
);

CREATE TABLE comment (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT REFERENCES wa_user(id) ON DELETE CASCADE,
    article_id BIGINT REFERENCES article(id) ON DELETE CASCADE,
    content TEXT NOT NULL DEFAULT '',
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    starred BOOLEAN NOT NULL DEFAULT FALSE,
    parent BIGINT REFERENCES comment(id) ON DELETE SET NULL
);

CREATE TABLE article_queue (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    article_id BIGINT NOT NULL REFERENCES article(id) ON DELETE CASCADE
);
